-- Study Packs: one row per uploaded document (docs/study-packs-contract.md). The file itself lives
-- on disk at storage_path (relative to app.storage.root); chunks live in the vector store.
-- PostgreSQL syntax that also runs on H2 2.x — no TEXT/CLOB, so error_message is a bounded VARCHAR.
CREATE TABLE study_packs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    extension VARCHAR(10) NOT NULL,
    storage_path VARCHAR(512),
    size_bytes BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    page_count INT,
    chunk_count INT,
    parser VARCHAR(50),
    ocr_used BOOLEAN,
    error_code VARCHAR(50),
    error_message VARCHAR(2000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_study_packs_owner FOREIGN KEY (owner_id) REFERENCES users (id)
);

-- Backs both "my packs, newest first" and the per-user pack-count limit check.
CREATE INDEX idx_study_packs_owner_created ON study_packs (owner_id, created_at);
