-- Pack chat history (docs/study-packs-contract.md "Chat with a pack"). ON DELETE CASCADE: deleting
-- a pack (one DELETE on study_packs) removes its history in the same statement, with no extra
-- round trip or entity loading on the JPA side.
-- sources / cited_sources are JSONB snapshots of what the answer was based on, so the history
-- renders its citations without re-querying the vector store.
CREATE TABLE pack_chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pack_id BIGINT NOT NULL,
    role VARCHAR(10) NOT NULL,
    content TEXT NOT NULL,
    sources JSONB NOT NULL DEFAULT '[]'::jsonb,
    cited_sources JSONB NOT NULL DEFAULT '[]'::jsonb,
    prompt_tokens INT,
    completion_tokens INT,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_pack_chat_messages_pack FOREIGN KEY (pack_id) REFERENCES study_packs (id) ON DELETE CASCADE
);

-- Backs "last N messages of this pack" (history page and prompt context) and the cascade delete.
CREATE INDEX idx_pack_chat_messages_pack_created ON pack_chat_messages (pack_id, created_at);
