-- Quiz from a pack (docs/study-packs-contract.md "Quiz from a pack"): the LLM-generated question
-- bank of one study pack. ON DELETE CASCADE: deleting a pack removes its bank in the same statement,
-- like its chat history (V18). Regenerating replaces every row of the pack in one transaction.
--   options: MCQ only, a JSON array of exactly 4 strings (NULL for CONCEPTUAL);
--   reference_answer: CONCEPTUAL only, what the grader compares the candidate's answer against;
--   source_*: where in the document the question comes from, so feedback can point back to it.
CREATE TABLE pack_quiz_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pack_id BIGINT NOT NULL,
    question_type VARCHAR(20) NOT NULL,
    difficulty VARCHAR(10) NOT NULL,
    prompt TEXT NOT NULL,
    options JSONB,
    correct_option_index INT,
    explanation TEXT,
    reference_answer TEXT,
    source_page INT,
    source_section VARCHAR(500),
    source_chunk_index INT,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_pack_quiz_questions_pack FOREIGN KEY (pack_id) REFERENCES study_packs (id) ON DELETE CASCADE
);

-- Backs question picking (all of a pack's questions of one type), the per-type counts that size a
-- quiz's sections, the replace-on-regenerate delete and the cascade delete.
CREATE INDEX idx_pack_quiz_questions_pack ON pack_quiz_questions (pack_id);

-- Bank status on the pack itself (PackDto.quizStatus / quizQuestionCount / quizErrorMessage).
-- Existing packs have no bank yet: NONE / 0.
ALTER TABLE study_packs ADD COLUMN quiz_status VARCHAR(20) NOT NULL DEFAULT 'NONE';
ALTER TABLE study_packs ADD COLUMN quiz_question_count INT NOT NULL DEFAULT 0;
ALTER TABLE study_packs ADD COLUMN quiz_error_message VARCHAR(500);
