-- Flashcards from a pack (docs/study-packs-contract.md "Flashcards from a pack"): the LLM-generated
-- deck of one study pack, each card carrying its own SM-2 spaced-repetition schedule. ON DELETE
-- CASCADE: deleting a pack removes its deck in the same statement, like its quiz bank (V19).
-- Regenerating replaces every row of the pack in one transaction.
--   ease_factor / interval_days / repetitions / due_at: SM-2 state, reviewed independently per card
--     (a pack is only ever studied by its own owner, so no separate per-user review table is needed);
--   source_*: where in the document the card comes from, so a card can point back to it.
CREATE TABLE pack_flashcards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pack_id BIGINT NOT NULL,
    front TEXT NOT NULL,
    back TEXT NOT NULL,
    source_page INT,
    source_section VARCHAR(500),
    source_chunk_index INT,
    ease_factor DOUBLE PRECISION NOT NULL DEFAULT 2.5,
    interval_days INT NOT NULL DEFAULT 0,
    repetitions INT NOT NULL DEFAULT 0,
    due_at TIMESTAMP NOT NULL,
    last_reviewed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_pack_flashcards_pack FOREIGN KEY (pack_id) REFERENCES study_packs (id) ON DELETE CASCADE
);

-- Backs "all of a pack's cards", the replace-on-regenerate delete and the cascade delete.
CREATE INDEX idx_pack_flashcards_pack ON pack_flashcards (pack_id);

-- Backs "cards due now for this pack", ordered oldest-due-first.
CREATE INDEX idx_pack_flashcards_pack_due ON pack_flashcards (pack_id, due_at);

-- Deck status on the pack itself (PackDto.flashcardStatus / flashcardCount / flashcardErrorMessage).
-- Existing packs have no deck yet: NONE / 0.
ALTER TABLE study_packs ADD COLUMN flashcard_status VARCHAR(20) NOT NULL DEFAULT 'NONE';
ALTER TABLE study_packs ADD COLUMN flashcard_count INT NOT NULL DEFAULT 0;
ALTER TABLE study_packs ADD COLUMN flashcard_error_message VARCHAR(500);
