-- Course from a pack (docs/study-packs-contract.md "Course from a pack"): the LLM-generated course
-- outline of one study pack. ON DELETE CASCADE: deleting a pack removes its outline in the same
-- statement, like its quiz bank (V19) and flashcard deck (V21). Regenerating replaces every row.
--   module_index / module_title / lesson_index_in_module: a module is not a separate table, the
--     same way a quiz bank has no separate "section" row;
--   source_chunk_start / source_chunk_end: the contiguous, non-overlapping slice of the pack's
--     chunks this lesson is written from (assigned at generation time, read lazily);
--   content: null until the lesson is first opened (generated then, one LLM call, cached here);
--   completed: plain per-pack state — a pack is only ever studied by its own owner.
CREATE TABLE pack_course_lessons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pack_id BIGINT NOT NULL,
    module_index INT NOT NULL,
    module_title VARCHAR(150) NOT NULL,
    lesson_index_in_module INT NOT NULL,
    title VARCHAR(200) NOT NULL,
    summary VARCHAR(400) NOT NULL,
    content TEXT,
    source_chunk_start INT NOT NULL,
    source_chunk_end INT NOT NULL,
    source_page INT,
    source_section VARCHAR(500),
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_pack_course_lessons_pack FOREIGN KEY (pack_id) REFERENCES study_packs (id) ON DELETE CASCADE
);

-- Backs "all of a pack's lessons in reading order", the replace-on-regenerate delete and the
-- cascade delete.
CREATE INDEX idx_pack_course_lessons_pack ON pack_course_lessons (pack_id, module_index, lesson_index_in_module);

-- Outline status on the pack itself (PackDto.courseStatus / courseLessonCount / courseErrorMessage).
-- Existing packs have no outline yet: NONE / 0.
ALTER TABLE study_packs ADD COLUMN course_status VARCHAR(20) NOT NULL DEFAULT 'NONE';
ALTER TABLE study_packs ADD COLUMN course_lesson_count INT NOT NULL DEFAULT 0;
ALTER TABLE study_packs ADD COLUMN course_error_message VARCHAR(500);
