-- Transactional outbox: a Kafka message to send, written in the SAME transaction as the business
-- row it describes (e.g. the new StudyPack row on upload), so the two can never diverge — either
-- both commit (the pack exists AND its outbox row will eventually be sent) or neither does. A
-- separate poller (OutboxPublisher) sends pending rows and deletes them on success; previously
-- the Kafka send only happened as a fire-and-forget async call after commit, so a send that failed
-- (broker down, network blip) was simply logged and lost, leaving the pack stuck QUEUED forever.
--   status: PENDING (not yet sent) or FAILED (gave up after app.outbox.max-attempts — needs
--     manual attention; still visible here, not deleted, unlike a row that sent successfully).
--   trace_id: the HTTP request's correlation id (CorrelationIdFilter), sent as a Kafka header so
--     logs for the original request and the async Kafka handling of it can be grepped together.
CREATE TABLE outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic VARCHAR(100) NOT NULL,
    message_key VARCHAR(100) NOT NULL,
    payload TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    attempts INT NOT NULL DEFAULT 0,
    last_error VARCHAR(1000),
    trace_id VARCHAR(100),
    created_at TIMESTAMP NOT NULL,
    last_attempt_at TIMESTAMP
);

-- Backs the poller's "oldest pending rows first" claim query.
CREATE INDEX idx_outbox_events_status ON outbox_events (status, id);
