CREATE TABLE answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    question_id BIGINT NOT NULL,
    answer_text TEXT NOT NULL,
    code_submission TEXT,
    submitted_at TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_answers_question UNIQUE (question_id),
    CONSTRAINT fk_answers_question FOREIGN KEY (question_id) REFERENCES questions (id)
);
